name: Run CI checks

on: [pull_request]

jobs:
  test-affected:
    runs-on: ubuntu-latest
    name: Test Store
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: yarn run nx affected:lint --parallel --base=origin/master
      - run: yarn run nx affected:test --parallel --base=origin/master
