name: Run CI checks

on: [pull_request]

jobs:
  test-affected:
    runs-on: ubuntu-latest
    name: Test Store
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: yarn run nx affected --target=test
